### ISSUE TITLE
TOC-progress plugin does not resize

### ISSUE THREAD

**Issue by lechten** [Sonaryr/reveal.js-coursemod#19]
I'd like to use your plugin in combination with the [TOC-Progess plugin](https://github.com/e-gor/Reveal.js-TOC-Progress), which adds a footer without class, with fixed id `#toc-progress-footer`. That footer does not change its size when changing to the coursemod view. If I add the footer's id as new [line 14 of coursemod.css](https://github.com/Sonaryr/reveal.js-coursemod/blob/master/coursemod/coursemod.css#L14), resizing works. 

Would you accept such a change as PR? Have you got a suggestion how to use both plugins simultaneously?

**Comment by Sonaryr** [comment]
Since this is a specific case for 2 plugins that mismatch. I would suggest you add an extra css file to your specific presentation that handles that styling

**Comment by lechten** [comment]
I'll do that. Thanks for the answer.
