### ISSUE TITLE
Printing needs fixing

### ISSUE THREAD

**Issue by egrosclaude** [Sonaryr/reveal.js-coursemod#2]
Print PDF css gets understandably confused by the new format. 
Might there be an option to print only slides or slides + notes? In the meantime, printing only slides like before is enough, as you can easily crank up some script to extract and format notes as a separate text-only handout.

**Comment by Sonaryr** [comment]
Will check it, thanks. Never used the print before.

**Comment by Sonaryr** [comment]
Should be fixed now (disabled the plugin when print-pdf is active)
