### ISSUE TITLE
Add default settings for slides

### ISSUE THREAD

**Issue by Sonaryr** [Sonaryr/reveal.js-coursemod#3]
Be able to set the shown indicator seperatly per slide

**Comment by Sonaryr** [comment]
Implemented in #8

**Comment by egrosclaude** [comment]
I'm having an issue with this: I set coursemod as enabled and shown as true. Then I set some slides to  data-coursemod-shown="false". All those slides not having data-coursemod-shown attribute should hence follow the default behavior. But the only slides where notes are shown are those immediately following those for which data-coursemod-shown is false.

Let's say the individual "shown" status is the following:
Slide 1 - false
Slide 2 - default
Slide 3 - default
Slide 4 - default
Slide 5 - false
Slide 6 - default

I'd expect slides 2, 3, 4 and 6 to show notes. However, only slides 2 and 6 show notes.

**Comment by egrosclaude** [comment]
Also, course mode shows OK when the browser window is refreshed, but fails again when the user navigates to another slide.

**Comment by Sonaryr** [comment]
Was caused by premature optimalisation. Fixed now.

**Comment by egrosclaude** [comment]
I agree, it's fixed!

Not important but you may want to give it a look: hot key toggles mode even when the individual slide has data-coursemod-shown = "false".
