### ISSUE TITLE
Absolute positioning of some elements

### ISSUE THREAD

**Issue by egrosclaude** [Sonaryr/reveal.js-coursemod#4]
The audio-slideshow plugin sound control bar still shows at the absolute center of the window, not the slide subwindow's. That way it bumps over other controls (see https://egrosclaude.github.io/RDCI/Introducción.html)

Absolute-positioned items in general are guaranteed to be a hassle...

**Comment by Sonaryr** [comment]
Should be fixed now. If you do find an element that is still not aligned correctly please do not hesitate to make a pull request.

**Comment by egrosclaude** [comment]
This still keeps occurring in Chrome and FF:
![image](https://cloud.githubusercontent.com/assets/1987096/19280018/4fbbbdc8-8fba-11e6-821b-50748b6f5b41.png)

**Comment by Sonaryr** [comment]
apparantly the position for the audio controls was done on element block overriding my css. fixed this by making my rule more important
